name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test - ${{ github.event_name }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Styleguide-Checks
      run: |
        ./scripts/check_styleguide.sh
    - name: Test with pytest
      run: |
        ./scripts/check_tests.sh
    - name: Coverage with pytest
      run: |
        ./scripts/check_coverage.sh
